### ISSUE TITLE
Error: Settings Inaccessible

### ISSUE THREAD

**Issue by BrandonKMLee** [louisbarclay/nudge#121]
Currently in `chrome-extension://dmhgdnbkjkejeddddlklojinngaideac/html/pages/sites.html#options`
```
"Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at HTMLInputElement.<anonymous> (sites.js:151)"
```

also in `chrome-extension://dmhgdnbkjkejeddddlklojinngaideac/html/pages/popup.html#` the settings page are practically unclickable unless going into Brave browser settings.

The settings are also jammed.

**Comment by louisbarclay** [comment]
Should be fixed in latest update to Chrome Web Store.
