### ISSUE TITLE
LinkedIn: main feed blocker not working anymore (including fix!)

### ISSUE THREAD

**Issue by th0rgall** [louisbarclay/nudge#124]
The LinkedIn `feed` (Main feed) and `feed_and_post` (News feed) blockers are not working anymore.

Here are hidee definitions that do work (2nd Sheet tab): https://docs.google.com/spreadsheets/d/137VLjd54RrE3894RmX2-kKRSoBTEWAMO0VGk4wKpK6o/edit#gid=1887861577

I also included description renaming proposals
- "News feed" -> "News feed & post"
- "Main feed" -> "News feed only"

The reason they weren't working anymore is that "Feed Updates" `innerText` got compared to an `innerHTML` inside the DOM that has more whitespace padding & 2 newlines. The sheet definitions above include this exact `innerHTML`, including whitespace.
 
<img width="495" alt="Screenshot 2021-10-04 at 17 23 16" src="https://user-images.githubusercontent.com/11543641/135871650-b907733f-640d-4f48-91c5-9e7bafd088af.png">

Update 10/05: I also fixed `instagram.com-feed`, I'll continue adding hidee definition updates to my spreadsheet ~; putting the updates ones in a new sheet.~

Update 10/20: I'm fixing sites & adding new sites in my hidee sheet. If anyone ever updates the main hidees, ask me to send you the entries I changed/added/fixed, I'll look in the Google Sheet History (or just copy mine as-is).

**Comment by BrandonKMLee** [comment]
Current issues https://github.com/louisbarclay/nudge/issues/121

**Comment by th0rgall** [comment]
Hey @BrandonKMLee, I understand you want to get that issue fixed, but in Github Issues, you should keep the discussion to the issue at hand!

I haven't looked at that issue in Brave. You can try to debug it yourself, preferably after setting up the latest development extension, see instructions here https://github.com/louisbarclay/nudge/blob/master/instructions.md. The current development version of Nudge works for me in Chrome. I think it's likely that the issue you refer to is either Brave-specific, related to this issue I fixed already https://github.com/louisbarclay/nudge/issues/118, or related to another reported issue.

**Comment by louisbarclay** [comment]
I have shipped a new version to the Chrome Web Store which includes all of @th0rgall's fantastic updates to Hidees, including these. I've also made @th0rgall admin on the Google Sheet that controls Hidees to more easily modify these in future if you want to.
