### ISSUE TITLE
Extension from Chrome Store not working

### ISSUE THREAD

**Issue by berezovskyi** [louisbarclay/nudge#125]
On the setup screen on a newly installed Chrome, I try to add a site to the list but get a JS exception:

![image](https://user-images.githubusercontent.com/64734/136434495-1b164433-4794-4b05-a4af-4ebe6fb4f5eb.png)

Do I understand correctly that the extension is no longer maintained due to https://news.ycombinator.com/item?id=28788821?

**Comment by chewy74** [comment]
i get a 404 error trying to install from the chrome store

**Comment by louisbarclay** [comment]
I have shipped a new version to the Chrome Web Store which includes the latest development version and should therefore fix this!
