### ISSUE TITLE
Invalid icon/emoji in Options back title

### ISSUE THREAD

**Issue by th0rgall** [louisbarclay/nudge#126]
<img width="917" alt="Screenshot 2021-10-20 at 13 38 07" src="https://user-images.githubusercontent.com/11543641/138078157-1b1bd356-29a7-4415-bb53-c421daa2514f.png">
<img width="785" alt="Screenshot 2021-10-20 at 13 40 12" src="https://user-images.githubusercontent.com/11543641/138078463-392d6f4f-f68c-43b2-ae37-26a23e701348.png">

A trivial issue, but still an issue. On the left of the "Options" back link in the Choose Sites (or other) settings pages, an icon is included that my computer can't render, see screenshots.
- This is the symbol: 🠐
- This is the line of code: https://github.com/louisbarclay/nudge/blob/209acc27adf06ba4b3a0dc9db14f7357dd921876/extension/js/options/option.js#L46
- https://www.google.com/search?client=safari&rls=en&q=%F0%9F%A0%90&ie=UTF-8&oe=UTF-8 shows that this is the unicode symbol "Leftwards Arrow with Small Equilateral Arrowhead: U+1F810" - all sites that present this icon result in the same dummy.

My system: 
- macOS 11.5.2
- Chrome 94.0.4606.81
- Nudge version: current dev https://github.com/louisbarclay/nudge/tree/b3f84b0912c4ff1cd2463a75280bd2028e3c87cd

Possibly this works only on Windows or certain Linux systems.

Suggested fix: use another more widely supported Unicode symbol for the arrow, or replace with an .svg. ← / "leftwards arrow" is probably a good candidate.

**Comment by louisbarclay** [comment]
Thanks for spotting! Should be fixed in https://github.com/louisbarclay/nudge/commit/13106791548469b97fda510d9ea0489ec7916110
